"""Tests for textplate CLI commands."""

from pathlib import Path

from typer.testing import CliRunner

from textplate.cli import app
from textplate.watch import format_interval, parse_interval

import pytest

FIXTURES = Path(__file__).parent / "fixtures"
runner = CliRunner()


# --- CLI press ---


class TestCLI:
    def test_press_stdout(self):
        result = runner.invoke(app, ["press", str(FIXTURES / "simple.textplate.md"), "--stdout"])
        assert result.exit_code == 0
        assert "Hello, world!" in result.stdout
        assert "**intro** section" in result.stdout
        assert "Generated by textplate" in result.stdout

    def test_press_writes_file(self, tmp_path):
        # Copy fixtures to tmp_path so output goes there
        template = FIXTURES.joinpath("simple.textplate.md").read_text()
        tmpl_file = tmp_path / "doc.textplate.md"
        tmpl_file.write_text(template)

        # Copy referenced files
        (tmp_path / "greeting.txt").write_text(FIXTURES.joinpath("greeting.txt").read_text())
        (tmp_path / "snippets.md").write_text(FIXTURES.joinpath("snippets.md").read_text())

        result = runner.invoke(app, ["press", str(tmpl_file)])
        assert result.exit_code == 0

        out_file = tmp_path / "doc.md"
        assert out_file.exists()
        content = out_file.read_text()
        assert "Hello, world!" in content
        assert "Generated by textplate" in content

    def test_press_missing_file(self):
        result = runner.invoke(app, ["press", "/nonexistent/file.md"])
        assert result.exit_code == 1

    def test_press_unresolvable_reference(self, tmp_path):
        tmpl = tmp_path / "bad.textplate.md"
        tmpl.write_text("[](text::./nope.md)")
        result = runner.invoke(app, ["press", str(tmpl)])
        assert result.exit_code == 1
        assert "Error" in result.stdout or "Error" in (result.stderr or "")


# --- Meta commands ---


class TestMetaCommands:
    def test_tool_description(self):
        result = runner.invoke(app, ["tool-description"])
        assert result.exit_code == 0
        assert "textplate" in result.stdout
        assert "text::" in result.stdout

    def test_tool_description_short(self):
        result = runner.invoke(app, ["tool-description-short"])
        assert result.exit_code == 0
        assert "textplate" in result.stdout


# --- Interval parsing ---


class TestParseInterval:
    def test_seconds(self):
        assert parse_interval("5s") == 5.0

    def test_minutes(self):
        assert parse_interval("2m") == 120.0

    def test_hours(self):
        assert parse_interval("1h") == 3600.0

    def test_days(self):
        assert parse_interval("1d") == 86400.0

    def test_fractional(self):
        assert parse_interval("1.5h") == 5400.0

    def test_case_insensitive(self):
        assert parse_interval("5S") == 5.0
        assert parse_interval("2M") == 120.0

    def test_whitespace(self):
        assert parse_interval("  5s  ") == 5.0

    def test_space_between(self):
        assert parse_interval("5 s") == 5.0

    def test_invalid_unit(self):
        with pytest.raises(ValueError, match="Invalid interval"):
            parse_interval("5x")

    def test_no_unit(self):
        with pytest.raises(ValueError, match="Invalid interval"):
            parse_interval("5")

    def test_empty(self):
        with pytest.raises(ValueError, match="Invalid interval"):
            parse_interval("")

    def test_just_unit(self):
        with pytest.raises(ValueError, match="Invalid interval"):
            parse_interval("s")


class TestFormatInterval:
    def test_seconds(self):
        assert format_interval(5) == "5s"

    def test_fractional_seconds(self):
        assert format_interval(2.5) == "2.5s"

    def test_minutes(self):
        assert format_interval(120) == "2m"

    def test_hours(self):
        assert format_interval(3600) == "1h"

    def test_days(self):
        assert format_interval(86400) == "1d"


# --- Watch CLI ---


class TestWatchCLI:
    def test_watch_missing_file(self):
        result = runner.invoke(app, ["watch", "/nonexistent/file.md"])
        assert result.exit_code == 1

    def test_watch_bad_interval(self, tmp_path):
        tmpl = tmp_path / "x.textplate.md"
        tmpl.write_text("hello")
        result = runner.invoke(app, ["watch", str(tmpl), "--every", "5x"])
        assert result.exit_code == 1

    def test_watch_too_small_interval(self, tmp_path):
        tmpl = tmp_path / "x.textplate.md"
        tmpl.write_text("hello")
        result = runner.invoke(app, ["watch", str(tmpl), "--every", "0.1s"])
        assert result.exit_code == 1
