"""Agent-oriented descriptions for textplate."""

TOOL_DESCRIPTION = """\
textplate — Markdown-based templating tool.

Compose documents from reusable markdown snippets using text:: link syntax.
Write normal markdown with special references, then "press" to generate clean
output with all references resolved inline.

SYNTAX:
  [label](text::./path/to/file.md)           Include entire file
  [label](text::./path/to/file.md#section)   Include a specific section
  [label](text::./path/to/file.md#section!)  Include section with its heading

Sections are addressed by GitHub-style heading slugs:
  ## My Section  →  #my-section
  ## What's New? →  #whats-new

COMMANDS:

  textplate press <file>
    Resolve all text:: references and produce plain markdown.
    Options:
      --stdout        Print to stdout instead of writing file
      --verbose, -v   Show output path after pressing

  textplate watch <file>
    Continuously re-press on an interval.
    Options:
      --every, -e     Interval (e.g. 5s, 30s, 2m, 1h) [default: 5s]
      --strict        Exit on first error
      --verbose, -v   Show status after each press
      --no-progress   Disable animated progress bar

OUTPUT NAMING:
  foo.textplate.md  →  foo.md          (clean output)
  other.md          →  other.filled.md (safe, avoids overwriting)

Output files get a <!-- Generated by textplate --> header comment.

BEHAVIOR:
  - Strict mode: all references must resolve or entire operation fails
  - No recursion: resolved content with text:: links is NOT re-resolved
  - Section extraction skips headings inside fenced code blocks
  - Sections include sub-headings (## captures ### within it)

TYPICAL WORKFLOW:
  1. Create template with text:: links to source files
  2. textplate press template.textplate.md
  3. Review output — clean markdown with all references inlined
  4. Use textplate watch for continuous regeneration during editing

WHEN TO USE:
  - Composing documentation from reusable snippets
  - Building READMEs that pull from multiple source files
  - Any document that references content from other markdown files
"""

TOOL_DESCRIPTION_SHORT = """\
### `textplate`

Markdown templating tool — compose documents from reusable snippets via
`text::` link syntax. `textplate press file.textplate.md` resolves all
references into plain markdown. `textplate watch` for continuous mode.

Syntax: `[label](text::./file.md#section)` to include a section,
`[label](text::./file.md)` for entire files.
"""

COMMAND_HELP = {
    "press": (
        "Resolve all text:: references in a template file and produce plain markdown.\n\n"
        "Usage: textplate press <file> [--stdout] [--verbose]\n\n"
        "The template file is processed strictly — all references must resolve\n"
        "or the entire operation fails. Output is written to a file derived from\n"
        "the input name (foo.textplate.md → foo.md) unless --stdout is used."
    ),
    "watch": (
        "Watch a template file and re-press it on a regular interval.\n\n"
        "Usage: textplate watch <file> [--every 5s] [--strict] [--verbose] [--no-progress]\n\n"
        "Continuously re-presses the template. Errors are logged by default;\n"
        "use --strict to exit on first error. Minimum interval is 0.5s."
    ),
}
